#!/bin/sh
# vim:set ft=sh:

# Tiny Cloud IMDS ifupdown-ng executor

case "$PHASE" in
post-up)
	/sbin/imds-net-sync
	;;
pre-down)
	# TODO: someday make imds-net-sync a daemon
	# /sbin/imds-net-sync -k
	;;
*) ;;
esac
