test-default:
  image: alpine:latest
  stage: test
  script:
    - apk add make kyua yx xz lz4 zstd
    - make -j $(nproc) check
  tags:
    - docker-alpine
    - x86_64

test-dash:
  extends: test-default
  before_script:
    - apk add dash
    - ln -sf /usr/bin/dash /bin/sh

test-oksh:
  extends: test-default
  before_script:
    - apk add oksh
    - ln -sf /bin/oksh /bin/sh

# disabled - yash hates 'local'
#test-yash:
#  extends: test-default
#  before_script:
#    - apk add yash
#    - ln -sf /usr/bin/yash /bin/sh

test-zsh:
  extends: test-default
  before_script:
    - apk add zsh
    - ln -sf /bin/zsh /bin/sh
